# ruff.toml
line-length = 88
target-version = "py310"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = ["E", "F", "I"]
ignore = []
fixable = ["ALL"]
unfixable = []


